version: "3.7"

services:
  o_ubt: # docker build -t o_ubt_image --file Dockerfile_o_ubt .
    image: o_ubt_image
    build:
      context: .
      dockerfile: Dockerfile_o_ubt

    # docker run -d -p 8022:22 -v ./py:/py405_open_stst/py --name o_ubt o_ubt_image  
    container_name: o_ubt
    # tty: true 
    stdin_open: true # 없으면 시작하자 마자 exit

    ports:
      - "8022:22"  

    # command: 

    volumes:
      - ./py:/py405_open_stst/py
