version: "0.1"

services:
  o_ubt:
    image: ubuntu:22.04
    container_name: o_ubt
    # tty: true 
    stdin_open: true # 없으면 시작하자 마자 exit
    
    volumes:
      - .:/root/py405_open_stat

    