version: "3.7"

services:
  o_maria:
    image: mariadb:10.11.2
    container_name: o_maria
    volumes:
      - ./mariadb/data:/var/lib/mysql  
      - ./mariadb/init:/docker-entrypoint-initdb.d
    
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      # - MARIADB_ROOT_PASSWORD_HASH=*DB469070DB0AD0CA0B93040D166D7FC4713D6961
      # - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      # - MARIADB_RANDOM_ROOT_PASSWORD=yes
      # - MYSQL_DATABASE=finance
      # - MYSQL_USER=u_fina
      # - MYSQL_PASSWORD=finapassword
      - TZ=Asia/Seoul
    command: 
      - --port=3666
      - --lower_case_table_names=1
      - --default-time-zone=Asia/Seoul
    ports:
      - "3666:3666"  
    restart: always
 
  o_ubt: # docker build -t o_ubt_image --file Dockerfile_o_ubt .
    depends_on:
      - o_maria
    image: o_ubt_image
    build:
      context: .
      dockerfile: Dockerfile_o_ubt

    # docker run -d -p 8022:22 -v ./py:/py405_open_stst/py --name o_ubt o_ubt_image  
    container_name: o_ubt
    # tty: true 
    stdin_open: true # 없으면 시작하자 마자 exit

    environment:
      - TZ=Asia/Seoul
      - LANG=en_US.UTF-8

    ports:
      - "8022:22"  

    volumes:
      - ./:/py405_open_stst/
      - ./ssh-keys/id_rsa.pub:/root/.ssh/authorized_keys

    # command: >
    #   bash -c "ls"

  o_airf: 
    depends_on:
      - o_maria
      - o_ubt
    image: apache/airflow:2.6.0-python3.10
    #image: apache/airflow:latest
    container_name: o_airf
    tty: true # -t 
    stdin_open: true # -i 없으면 시작하자 마자 exit

    #privileged: true
    environment:
      # - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - TZ=Asia/Seoul
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql://u_airflow:${MARIADB_AIRFROW_PASSWORD}@o_maria:3666/airflow
      # - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW_CONN_MYSQL_CUSTOM=mysql://u_fina:${MARIADB_APP_FINANCE_PASSWORD}@o_maria:3666/finance

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      # - ./:/py405_open_stst/  # requirements.txt 때문에 했지만, airflow 를 위한 파이썬 패키지 환경은 변경하면 안될듯
      - ./ssh-keys:/home/airflow/.ssh

    command: > 
      bash -c "
               sed -i 's|default_timezone = utc|default_timezone = Asia/Seoul|g' /opt/airflow/airflow.cfg
               sed -i 's|default_ui_timezone = UTC|default_ui_timezone = Asia/Seoul|g' /opt/airflow/airflow.cfg
               ssh-keygen -f "/home/airflow/.ssh/known_hosts" -R "o_ubt"
               airflow db init && \
               airflow users create --username admin --password airfadminpw --firstname YH --lastname L --role Admin --email admin@example.org && \
               airflow webserver & \
               airflow scheduler 
              "
    ports: 
      - "8081:8080"  

  o_cadv:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: o_cadv
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8082:8080
    privileged: true
    devices:
      - /dev/kmsg

  o_ndex:
    image: prom/node-exporter:latest
    container_name: o_ndex
    restart: unless-stopped
    expose:
      - 9100
    ports:
      - 8083:9100

  o_prmth:
    image: prom/prometheus:latest
    container_name: o_prmth
    ports:
      - 8084:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus/data
    depends_on:
      - o_cadv
      - o_ndex

  o_graf:
    image: grafana/grafana:latest
    container_name: o_graf
    restart: unless-stopped
    links:
      - o_prmth:prometheus
    ports:
      - 8085:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=myadmin
      - GF_USERS_ALLOW_SIGN_UP=false  