FROM ubuntu:22.04

# MAINTAINER unlimit <unlimit.gcp@gmail.com>

# Ubuntu 패키지 소스 리스트를 수정하여 Kakao 미러 사이트를 사용하도록 변경합니다.
RUN sed -i 's/archive.ubuntu.com/mirror.kakao.com/g' /etc/apt/sources.list

# 필요한 패키지 및 소프트웨어 설치
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv

RUN apt-get install -y \
    openssh-server \
    nano \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# SSH 설정
RUN echo 'root:qwer!@34' | chpasswd
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# App 설정 
RUN mkdir /py405_open_stst 
RUN cd /py405_open_stst
COPY ./requirements.txt /py405_open_stst
RUN pip install -r /py405_open_stst/requirements.txt

# sshd 데몬 실행
CMD ["/usr/sbin/sshd", "-D"]

# 포트 노출
EXPOSE 22

# docker build -t o_ubt_image --file Dockerfile_o_ubt .
# docker run -d -p 8022:22 -v ./py:/py405_open_stst/py --name o_ubt o_ubt_image
# ssh root@192.168.0.108 -p 8022
