FROM ubuntu:22.04

# MAINTAINER unlimit <unlimit.gcp@gmail.com>

# 필요한 패키지 및 소프트웨어 설치
RUN apt-get update 

RUN apt-get install -y \
    python3 \
    python3-pip \
    python3-venv

RUN apt-get install -y \
    openssh-server \
    nano \
    curl \
    && rm -rf /var/lib/apt/lists/*

# SSH 설정
RUN echo 'root:qwer!@34' | chpasswd
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# sshd 데몬 실행
CMD ["/usr/sbin/sshd", "-D"]

# 포트 노출
EXPOSE 22

# docker build -t o_ubt_image --file Dockerfile_o_ubt .
# docker run -d -p 8022:22 -v ./py:/pyapp --name o_ubt o_ubt_image
# ssh root@192.168.0.108 -p 8022
