#docker_compose.yml

version: "2"

services:
  vault:
    image: vault:1.13.1
    container_name: vault
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
      - ./vault/file:/vault/file
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault-config.hcl